### ISSUE TITLE
Польза паттерна Builder

### ISSUE THREAD

**Issue by alexmikhalevich** [isergeyam/Pizza-factory#1]
Зачем нам для такого объекта паттерн Builder?
https://github.com/isergeyam/Pizza-factory/blob/d4460b3e53c343b405f691bcfce61e579a9f321d/include/Pizza.hpp#L7

**Comment by isergeyam** [comment]
Не совсем понял вопрос.... Объект не достаточно сложен для данного паттерна? Но это же просто демонстрация использования....

**Comment by alexmikhalevich** [comment]
Не, не в том дело. Помнишь, я на семинаре говорил про иммутабельность?

**Comment by isergeyam** [comment]
Fixed in 12721626257275b90454eee5861de835873f0ab9
